const pages = [
  `<article class="sheet cover-sheet" aria-label="Cover"><div class="cover-top"><span>NCG MAGAZINE</span><span>ISSUE 01 / 2026</span></div><div class="cover-title"><span>THE FRONT ROW EDITORIAL</span><h1>Fashioned<br><i>by Heritage.</i></h1><p>Streetwear · Live music · Culture</p></div><div class="cover-bottom"><span>STREET-STYLE SHOWDOWN</span><span>NAIROBI, KENYA</span></div></article>`,
  `<article class="sheet story-sheet" aria-label="The story"><div class="page-top"><span>02 / THE STORY</span><span>FASHIONED BY HERITAGE</span></div><div class="story-body"><p class="kicker">STREET-STYLE SHOWDOWN</p><h2>Where the street becomes a runway.</h2><p>The first Street-Style Showdown brought fashion and live music together at City Boy Est. Designers drew from heritage, contemporary streetwear and the energy of Nairobi’s creative community.</p><p>The event made space for experimentation, shared identity and a conversation between the runway and the room. This issue takes a closer look at that meeting point.</p><div class="story-rule"></div><p class="caption">A SOUL SOCIETY AFFAIR · NAIROBI</p></div><div class="page-foot"><span>NAIROBI CITY GIRLS</span><span>02</span></div></article>`,
  `<article class="sheet artwork-sheet" aria-label="Designed magazine spread"><a href="assets/canva-1.jpg" target="_blank" rel="noopener" aria-label="Open designed magazine page at full size"><img src="assets/canva-1.jpg" alt="Orange magazine spread featuring Street-Style Showdown photographs and editorial text"></a></article>`,
  `<article class="sheet credits-sheet" aria-label="Credits"><div class="page-top"><span>04 / CREDITS</span><span>THE FRONT ROW</span></div><div class="credits-body"><p class="kicker">ISSUE 01 · 24 FEBRUARY 2026</p><h2>Made in<br><i>Nairobi.</i></h2><dl><div><dt>Story</dt><dd>Owirriana</dd></div><div><dt>Photography</dt><dd>Sidoh Official</dd></div><div><dt>Magazine design</dt><dd>Owirriana</dd></div></dl><p>Fashioned by Heritage is a Nairobi City Girls Magazine feature on Street-Style Showdown.</p><a href="../../index.html#issues">Back to The Issues ↗</a></div><div class="page-foot"><span>NAIROBI CITY GIRLS MAGAZINE</span><span>04</span></div></article>`
];
const container=document.querySelector('#pages');const counter=document.querySelector('#counter');const bar=document.querySelector('#progress-bar');let index=0;let busy=false;
function render(direction=0){container.classList.remove('turn-next','turn-prev');container.innerHTML=pages[index];counter.textContent=String(index+1).padStart(2,'0')+' / '+String(pages.length).padStart(2,'0');bar.style.width=((index+1)/pages.length*100)+'%';for(const id of ['prev','prev-side'])document.getElementById(id).disabled=index===0;for(const id of ['next','next-side'])document.getElementById(id).disabled=index===pages.length-1;if(direction){container.classList.add(direction>0?'turn-next':'turn-prev');setTimeout(()=>container.classList.remove('turn-next','turn-prev'),450)}}
function go(to){if(busy||to<0||to>=pages.length||to===index)return;busy=true;const direction=to-index;index=to;render(direction);setTimeout(()=>busy=false,450)}
document.querySelector('#prev').onclick=document.querySelector('#prev-side').onclick=()=>go(index-1);document.querySelector('#next').onclick=document.querySelector('#next-side').onclick=()=>go(index+1);
document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')go(index+1);if(e.key==='ArrowLeft')go(index-1);if(e.key==='Escape'){document.querySelector('#contents').hidden=true;document.querySelector('#contents-button').setAttribute('aria-expanded','false')}});
const contents=document.querySelector('#contents');const contentsButton=document.querySelector('#contents-button');contentsButton.onclick=()=>{contents.hidden=!contents.hidden;contentsButton.setAttribute('aria-expanded',String(!contents.hidden))};contents.querySelectorAll('button').forEach(b=>b.onclick=()=>{go(Number(b.dataset.goto));contents.hidden=true;contentsButton.setAttribute('aria-expanded','false')});render();
